# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "创建文档"),
                            (2, "更新文档"),
                            (3, "删除文档"),
                            (4, "新建文档版本"),
                            (5, "更新某个版本"),
                            (6, "删除某个版本"),
                        ],
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[(1, "个人"), (2, "团队"), (3, "企业")], verbose_name="文档类型"
                    ),
                ),
                ("document_id", models.IntegerField(verbose_name="文档ID")),
                (
                    "version_id",
                    models.IntegerField(blank=True, null=True, verbose_name="版本ID"),
                ),
                ("owner_id", models.IntegerField(verbose_name="所有者ID")),
            ],
            options={
                "verbose_name": "日志",
                "verbose_name_plural": "日志",
                "db_table": "dco_log",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=100, verbose_name="文档")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文档描述"
                    ),
                ),
                (
                    "owner",
                    models.IntegerField(
                        choices=[(1, "个人"), (2, "团队"), (3, "企业")],
                        verbose_name="文档所属者类型",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doc_avatars",
                        verbose_name="文档头像",
                    ),
                ),
                (
                    "version_counts",
                    models.IntegerField(default=0, verbose_name="版本号分配"),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档列表",
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="文档内容"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="版本说明"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "source_version",
                    models.IntegerField(default=0, verbose_name="源于哪个版本"),
                ),
            ],
            options={
                "verbose_name": "文档版本",
                "verbose_name_plural": "文档版本列表",
                "db_table": "doc_versions",
            },
        ),
        migrations.CreateModel(
            name="InnerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "file",
                    models.FileField(upload_to="inner_files", verbose_name="文档中的文件"),
                ),
            ],
            options={
                "verbose_name": "文档中文件",
                "verbose_name_plural": "文档中文件列表",
                "db_table": "inner_files",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=20, verbose_name="模板名")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "模板",
                "verbose_name_plural": "模板列表",
                "db_table": "templates",
            },
        ),
    ]
