# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0002_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="innerfile",
            name="affiliated_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inner_files",
                to="documents.document",
                verbose_name="基于哪个文档上传的",
            ),
        ),
        migrations.AddField(
            model_name="innerfile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inner_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="属于哪个用户",
            ),
        ),
        migrations.AddField(
            model_name="docversion",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.document",
                verbose_name="所属文档",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="collect_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="collect_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏的用户",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="companies.company",
                verbose_name="所属企业",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="create_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.template",
                verbose_name="文档模板",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属个人",
            ),
        ),
        migrations.AddField(
            model_name="doclog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
    ]
