# Generated by Django 4.2.13 on 2024-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="content",
            field=models.FileField(blank=True, null=True, upload_to="templates/"),
        ),
    ]
