# Generated by Django 4.2.13 on 2024-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_keyword_document_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="关键词"),
        ),
    ]
