# Generated by Django 4.2.13 on 2024-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_keyword_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="template_avatars/"
            ),
        ),
    ]
