# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被邀请",
            ),
        ),
    ]
