# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="企业名称"),
                ),
                ("description", models.TextField(verbose_name="企业描述")),
            ],
            options={
                "verbose_name": "企业",
                "verbose_name_plural": "公司列表",
                "db_table": "companies",
            },
        ),
    ]
