# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="企业创建者",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="administrators",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="团队管理员",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="affiliated_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="企业人员",
            ),
        ),
    ]
