# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("text", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[("bot", "Bot"), ("user", "User")], max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "对话记录",
                "verbose_name_plural": "对话记录列表",
                "db_table": "dialog",
            },
        ),
    ]
